image_width: 720
image_height: 640
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1829.35338302932, 0.000000, 360, 0.000000, 1829.77877605685, 320, 0.000000, 0.000000, 1.000000]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.03959299905078, 0.0608315048324367, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000]
projection_matrix:
  rows: 3
  cols: 4
  data: [1829.353383, 0.000000, 360, 0.000000, 0.000000, 1829.778776, 320, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]